import { getStore } from '@netlify/blobs';
import crypto from 'node:crypto';
import seed from '../../seed.json' with { type: 'json' };
const contentStore=getStore('lamthanh-cms'),mediaStore=getStore('lamthanh-media'),feedbackStore=getStore('lamthanh-feedback'),lookupStore=getStore('lamthanh-lookup'),accountStore=getStore('lamthanh-accounts');
const secret=process.env.CMS_SESSION_SECRET,envUser=process.env.CMS_ADMIN_USERNAME,envPass=process.env.CMS_ADMIN_PASSWORD,isConfigured=!!secret&&secret.length>=32&&!!envUser&&!!envPass;
const json=(body,status=200,headers={})=>({status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers},body:JSON.stringify(body)});
const sign=v=>crypto.createHmac('sha256',secret||'invalid').update(v).digest('base64url');
const hashPassword=p=>crypto.pbkdf2Sync(String(p),secret||'invalid',210000,32,'sha256').toString('base64url');
const makeToken=(u,role)=>{const p=Buffer.from(JSON.stringify({u,role,exp:Date.now()+8*3600e3})).toString('base64url');return `${p}.${sign(p)}`};
const getCookie=(req,n)=>(req.headers.get('cookie')||'').match(new RegExp(`(?:^|; )${n}=([^;]+)`))?.[1];
const session=req=>{try{const raw=getCookie(req,'lt_session');if(!raw)return null;const [p,s]=raw.split('.');if(!p||!s)return null;const e=sign(p),a=Buffer.from(s),b=Buffer.from(e);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return null;const v=JSON.parse(Buffer.from(p,'base64url').toString());return v.exp>Date.now()?v:null}catch{return null}};
const can=(s,roles)=>!!s&&roles.includes(s.role);const cookie=(t,maxAge)=>`lt_session=${t}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`;
const requireConfigured=()=>{if(!isConfigured)throw new Error('CMS chưa được cấu hình. Hãy đặt CMS_SESSION_SECRET (>=32 ký tự), CMS_ADMIN_USERNAME và CMS_ADMIN_PASSWORD trên Netlify.')};
const requireAuth=(req,roles=['admin','editor'])=>{const s=session(req);return can(s,roles)?s:null};
const originAllowed=req=>{if(!['POST','PUT','PATCH','DELETE'].includes(req.method))return true;const o=req.headers.get('origin');if(!o)return true;try{return o===new URL(req.url).origin}catch{return false}};
const PUBLIC_KEYS=['site','news','docs','procedures','schedule','stats','settings','navigation','quickLinks','banners'];
const publicContent=c=>Object.fromEntries(PUBLIC_KEYS.map(k=>[k,c?.[k]??(Array.isArray(seed[k])?[]:{})]));
const recordKey=id=>`record/${String(id)}`;const newId=()=>`${Date.now()}-${crypto.randomBytes(5).toString('hex')}`;
async function getContentRaw(){let v=await contentStore.get('content',{type:'json'});if(v)return v;v=publicContent(seed);await contentStore.setJSON('content',v);await contentStore.setJSON('content-meta',{version:1,updatedAt:new Date().toISOString()});for(const x of seed.feedback||[])await feedbackStore.setJSON(recordKey(x.id??newId()),{...x,id:x.id??newId()});for(const x of seed.lookupRecords||[])await lookupStore.setJSON(recordKey(x.id??newId()),{...x,id:x.id??newId()});return v}
async function getMeta(){return await contentStore.get('content-meta',{type:'json'})||{version:1,updatedAt:null}}
async function saveContent(data,version){const cur=await getMeta();if(version!=null&&Number(version)!==Number(cur.version))return{conflict:true,current:cur};const meta={version:Number(cur.version||0)+1,updatedAt:new Date().toISOString()};await contentStore.setJSON('content',publicContent(data));await contentStore.setJSON('content-meta',meta);return{conflict:false,meta}}
async function getAccounts(){requireConfigured();let a=await accountStore.get('accounts',{type:'json'});if(a)return a;a=[{username:envUser,displayName:'Quản trị viên',role:'admin',passwordHash:hashPassword(envPass),enabled:true,createdAt:new Date().toISOString()}];await accountStore.setJSON('accounts',a);return a}
async function listBlobs(store,prefix){const r=await store.list({prefix});return r.blobs||[]}
async function getRecords(store){const items=[];for(const b of await listBlobs(store,'record/')){const x=await store.get(b.key,{type:'json'});if(x)items.push(x)}return items}
export default async req=>{const url=new URL(req.url),path=url.pathname.replace(/\/$/,'');try{
if(!originAllowed(req))return json({error:'invalid_origin'},403);
if(path.endsWith('/content')&&req.method==='GET')return json({data:publicContent(await getContentRaw()),meta:await getMeta()});
if(path.endsWith('/session')&&req.method==='GET'){const s=session(req);return json({authenticated:!!s,user:s?.u||null,role:s?.role||null})}
if(path.endsWith('/login')&&req.method==='POST'){requireConfigured();const b=await req.json(),a=(await getAccounts()).find(x=>x.username===String(b.username||'').trim()&&x.enabled!==false);if(!a||hashPassword(String(b.password||''))!==a.passwordHash)return json({error:'Sai tên đăng nhập hoặc mật khẩu.'},401);return json({ok:true,user:a.username,role:a.role},200,{'Set-Cookie':cookie(makeToken(a.username,a.role),8*3600)})}
if(path.endsWith('/logout')&&req.method==='POST')return json({ok:true},200,{'Set-Cookie':cookie('',0)});
if(path.endsWith('/admin-data')&&req.method==='GET'){if(!requireAuth(req))return json({error:'unauthorized'},401);return json({data:publicContent(await getContentRaw()),meta:await getMeta(),feedback:await getRecords(feedbackStore),lookupRecords:await getRecords(lookupStore)})}
if(path.endsWith('/content')&&req.method==='PUT'){if(!requireAuth(req))return json({error:'unauthorized'},401);const b=await req.json();if(!b?.data||typeof b.data!=='object'||Array.isArray(b.data))return json({error:'Dữ liệu không hợp lệ.'},400);const r=await saveContent(b.data,b.version);if(r.conflict)return json({error:'Dữ liệu đã được thay đổi bởi phiên khác. Hãy tải lại trang.',meta:r.current},409);return json({ok:true,meta:r.meta})}
if(path.endsWith('/feedback')&&req.method==='POST'){const b=await req.json(),name=String(b.name||'').trim().slice(0,120),contact=String(b.contact||'').trim().slice(0,160),content=String(b.content||'').trim().slice(0,5000);if(!name||!contact||!content)return json({error:'Vui lòng nhập họ tên, thông tin liên hệ và nội dung.'},400);const item={id:newId(),name,contact,topic:String(b.topic||'').slice(0,160),date:new Date().toLocaleDateString('vi-VN'),status:'Mới',content,note:''};await feedbackStore.setJSON(recordKey(item.id),item);return json({ok:true,id:item.id})}
if(path.endsWith('/feedback')&&req.method==='GET'){if(!requireAuth(req))return json({error:'unauthorized'},401);return json({items:await getRecords(feedbackStore)})}
if(path.endsWith('/feedback')&&['PUT','DELETE'].includes(req.method)){if(!requireAuth(req))return json({error:'unauthorized'},401);const id=url.searchParams.get('id');if(!id)return json({error:'Thiếu id.'},400);if(req.method==='DELETE'){await feedbackStore.delete(recordKey(id));return json({ok:true})}const item=await feedbackStore.get(recordKey(id),{type:'json'});if(!item)return json({error:'Không tìm thấy phản ánh.'},404);const b=await req.json();item.status=['Mới','Đang xử lý','Đã xử lý'].includes(b.status)?b.status:item.status;item.note=String(b.note||'').slice(0,3000);await feedbackStore.setJSON(recordKey(id),item);return json({ok:true})}
if(path.endsWith('/lookup')&&req.method==='GET'){const code=String(url.searchParams.get('code')||'').trim();if(!code)return json({error:'Thiếu mã hồ sơ.'},400);const item=(await getRecords(lookupStore)).find(x=>String(x.code).toLowerCase()===code.toLowerCase());return item?json({found:true,item:{code:item.code,name:item.name,procedure:item.procedure,received:item.received,status:item.status,updated:item.updated,note:item.note||''}}):json({found:false})}
if(path.endsWith('/lookup')&&['POST','PUT','DELETE'].includes(req.method)){if(!requireAuth(req))return json({error:'unauthorized'},401);const b=await req.json().catch(()=>({})),id=url.searchParams.get('id')||b.id||newId();if(req.method==='DELETE'){await lookupStore.delete(recordKey(id));return json({ok:true})}const item={id,code:String(b.code||'').trim().slice(0,80),name:String(b.name||'').trim().slice(0,160),procedure:String(b.procedure||'').trim().slice(0,240),received:String(b.received||'').trim().slice(0,80),status:String(b.status||'Đang xử lý').slice(0,80),updated:String(b.updated||'').trim().slice(0,80),note:String(b.note||'').slice(0,3000)};if(!item.code||!item.procedure)return json({error:'Nhập mã hồ sơ và thủ tục.'},400);await lookupStore.setJSON(recordKey(id),item);return json({ok:true,item})}
if(path.endsWith('/accounts')&&req.method==='GET'){if(!requireAuth(req,['admin']))return json({error:'forbidden'},403);return json({items:(await getAccounts()).map(({passwordHash,...x})=>x)})}
if(path.endsWith('/accounts')&&req.method==='POST'){if(!requireAuth(req,['admin']))return json({error:'forbidden'},403);const b=await req.json(),username=String(b.username||'').trim(),password=String(b.password||'');if(!/^[a-zA-Z0-9._-]{3,40}$/.test(username)||password.length<10||!['admin','editor'].includes(b.role))return json({error:'Tên đăng nhập 3-40 ký tự; mật khẩu tối thiểu 10 ký tự; quyền không hợp lệ.'},400);const a=await getAccounts();if(a.some(x=>x.username===username))return json({error:'Tài khoản đã tồn tại.'},409);a.push({username,displayName:String(b.displayName||username).slice(0,120),role:b.role,passwordHash:hashPassword(password),enabled:b.enabled!==false,createdAt:new Date().toISOString()});await accountStore.setJSON('accounts',a);return json({ok:true})}
if(path.endsWith('/accounts')&&req.method==='PUT'){const s=requireAuth(req,['admin']);if(!s)return json({error:'forbidden'},403);const b=await req.json(),a=await getAccounts(),i=a.findIndex(x=>x.username===b.username);if(i<0)return json({error:'Không tìm thấy tài khoản.'},404);if(b.username===s.u&&b.enabled===false)return json({error:'Không thể khóa tài khoản đang đăng nhập.'},400);a[i]={...a[i],displayName:b.displayName==null?a[i].displayName:String(b.displayName).slice(0,120),role:b.role||a[i].role,enabled:b.enabled!==false};if(b.password){if(String(b.password).length<10)return json({error:'Mật khẩu tối thiểu 10 ký tự.'},400);a[i].passwordHash=hashPassword(b.password)}await accountStore.setJSON('accounts',a);return json({ok:true})}
if(path.endsWith('/accounts')&&req.method==='DELETE'){const s=requireAuth(req,['admin']);if(!s)return json({error:'forbidden'},403);const u=url.searchParams.get('username');if(!u||u===s.u)return json({error:'Không thể xóa tài khoản đang đăng nhập.'},400);await accountStore.setJSON('accounts',(await getAccounts()).filter(x=>x.username!==u));return json({ok:true})}
if(path.endsWith('/backup')&&req.method==='GET'){if(!requireAuth(req,['admin']))return json({error:'forbidden'},403);return json({content:publicContent(await getContentRaw()),feedback:await getRecords(feedbackStore),lookupRecords:await getRecords(lookupStore),meta:await getMeta(),exportedAt:new Date().toISOString()})}
if(path.endsWith('/backup')&&req.method==='POST'){if(!requireAuth(req,['admin']))return json({error:'forbidden'},403);const b=await req.json();if(!b.content||typeof b.content!=='object'||Array.isArray(b.content))return json({error:'Dữ liệu sao lưu không hợp lệ.'},400);const r=await saveContent(b.content,(await getMeta()).version);if(r.conflict)return json({error:'Dữ liệu đã thay đổi. Hãy tải lại.'},409);for(const x of await listBlobs(feedbackStore,'record/'))await feedbackStore.delete(x.key);for(const x of await listBlobs(lookupStore,'record/'))await lookupStore.delete(x.key);for(const x of b.feedback||[])if(x?.id)await feedbackStore.setJSON(recordKey(x.id),x);for(const x of b.lookupRecords||[])if(x?.id)await lookupStore.setJSON(recordKey(x.id),x);return json({ok:true,meta:r.meta})}
if(path.endsWith('/media')&&req.method==='GET'){if(!requireAuth(req))return json({error:'unauthorized'},401);return json({items:(await listBlobs(mediaStore,'uploads/')).map(b=>({key:b.key,url:`/.netlify/functions/cms/media/${encodeURIComponent(b.key.slice(8))}`}))})}
if(path.includes('/media/')&&req.method==='GET'){const name=decodeURIComponent(path.split('/media/')[1]||'');if(!/^[a-zA-Z0-9._-]{1,220}$/.test(name))return new Response('Bad request',{status:400});const blob=await mediaStore.get(`uploads/${name}`,{type:'arrayBuffer'});if(!blob)return new Response('Not found',{status:404});const ext=name.split('.').pop().toLowerCase(),types={png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',gif:'image/gif'};return new Response(blob,{status:200,headers:{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':'public,max-age=31536000,immutable','X-Content-Type-Options':'nosniff'}})}
if(path.endsWith('/media')&&req.method==='POST'){if(!requireAuth(req))return json({error:'unauthorized'},401);const file=(await req.formData()).get('file');if(!file||typeof file.arrayBuffer!=='function')return json({error:'Thiếu tệp.'},400);if(file.size>5*1024*1024)return json({error:'Ảnh vượt quá 5MB.'},413);const allowed=new Set(['image/png','image/jpeg','image/webp','image/gif']);if(!allowed.has(file.type))return json({error:'Chỉ hỗ trợ PNG, JPG, WEBP, GIF.'},415);const original=String(file.name||'image').toLowerCase(),ext=original.match(/\.(png|jpe?g|webp|gif)$/)?.[1].replace('jpeg','jpg')||'bin',safe=original.replace(/[^a-z0-9._-]/g,'-').slice(-100),key=`uploads/${Date.now()}-${crypto.randomBytes(6).toString('hex')}-${safe.replace(/\.[^.]+$/,'')}.${ext}`;await mediaStore.set(key,await file.arrayBuffer(),{metadata:{contentType:file.type}});return json({ok:true,key,url:`/.netlify/functions/cms/media/${encodeURIComponent(key.slice(8))}`})}
if(path.endsWith('/media')&&req.method==='DELETE'){if(!requireAuth(req))return json({error:'unauthorized'},401);const key=url.searchParams.get('key')||'';if(!/^uploads\/[a-zA-Z0-9._-]{1,260}$/.test(key))return json({error:'Tệp không hợp lệ.'},400);await mediaStore.delete(key);return json({ok:true})}
return json({error:'not_found'},404)}catch(error){console.error(error);return json({error:error.message||'Server error'},500)}};
