import './style.css';
const api=async(path,opt={})=>{const r=await fetch('/.netlify/functions/cms'+path,{credentials:'include',...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const t=await r.text();let d={};try{d=JSON.parse(t)}catch{}if(!r.ok)throw new Error(d.error||t||r.statusText);return d};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data={},meta={},auth=null,tab='overview';
async function load(){try{const r=await api('/content');data=r.data;meta=r.meta}catch(e){data={site:{name:'Trung tâm PVHCC xã Lam Thành',shortName:'Trung tâm PVHCC xã Lam Thành'},news:[],docs:[],procedures:[],schedule:[],stats:{},settings:{bannerTitle:'Trung tâm PVHCC xã Lam Thành',bannerText:'Phục vụ người dân'},navigation:[],quickLinks:[],banners:[]};meta={version:null}}}
const nav=()=>{const n=(data.navigation||[]).filter(x=>x.enabled!==false).sort((a,b)=>(a.order||0)-(b.order||0));return n.map(x=>`<a href="${esc(x.url)}">${esc(x.label)}</a>`).join('')};
function header(){return `<div class="top"><div class="wrap topin"><span>${esc(data.site?.hours)}</span><span>${esc(data.site?.email)} · ${esc(data.site?.hotline)}</span></div></div><header class="brand wrap"><a class="logo" href="/"><span class="seal">LT</span><span><b>${esc(data.site?.name)}</b><small>${esc(data.site?.commune)}, ${esc(data.site?.province)}</small></span></a><button class="hamb" onclick="document.body.classList.toggle('navopen')">☰</button></header><nav><div class="wrap navin">${nav()}<a href="/quan-tri" class="adminlink">Quản trị</a></div></nav>`}
function footer(){return `<footer><div class="wrap footgrid"><div><h3>${esc(data.site?.shortName)}</h3><p>${esc(data.site?.motto)}</p></div><div><h4>Liên hệ</h4><p>${esc(data.site?.address)}</p><p>${esc(data.site?.email)}</p><p>${esc(data.site?.hotline)}</p></div><div><h4>Giờ làm việc</h4><p>${esc(data.site?.hours)}</p></div></div><div class="copy">© 2026 ${esc(data.site?.name)}</div></footer>`}
const layout=(title,body)=>`${header()}<main><div class="wrap"><div class="crumb"><a href="/">Trang chủ</a> / ${esc(title)}</div>${body}</div></main>${footer()}`;
const card=x=>`<article class="card"><a href="/tin-tuc/${encodeURIComponent(x.slug||'')}"><img src="${esc(x.image||'/news-1.svg')}" alt=""></a><div><span class="tag">${esc(x.category)}</span><h3><a href="/tin-tuc/${encodeURIComponent(x.slug||'')}">${esc(x.title)}</a></h3><time>${esc(x.date)}</time><p>${esc(x.excerpt)}</p></div></article>`;
function home(){const b=(data.banners||[]).find(x=>x.enabled!==false)||{title:data.settings?.bannerTitle,text:data.settings?.bannerText,image:'/hero.svg',buttonText:'Tra cứu thủ tục',buttonUrl:'/thu-tuc'};return `${header()}<main><section class="hero"><div class="wrap hero-in"><div><span class="eyebrow">${esc(data.site?.shortName)}</span><h1>${esc(b.title)}</h1><p>${esc(b.text)}</p><div class="actions"><a class="btn" href="${esc(b.buttonUrl)}">${esc(b.buttonText)}</a><a class="btn ghost" href="/tin-tuc">Tin tức</a></div></div><img src="${esc(b.image||'/hero.svg')}" alt=""></div></section><div class="wrap home"><div class="sectionhead"><h2>Tin tức — Thông báo</h2><a href="/tin-tuc">Xem tất cả →</a></div><div class="newsgrid">${(data.news||[]).slice(0,4).map(card).join('')}</div><section class="quick"><h2>Tra cứu nhanh</h2><div class="quickgrid">${(data.quickLinks||[]).filter(x=>x.enabled!==false).map(x=>`<a href="${esc(x.url)}"><b>${esc(x.title)}</b><span>${esc(x.text)}</span></a>`).join('')}</div></section></div></main>${footer()}`}
function news(){return layout('Tin tức',`<div class="sectionhead"><h1>Tin tức — Thông báo</h1></div><div class="newsgrid">${(data.news||[]).map(card).join('')}</div>`)}
function newsDetail(slug){const x=(data.news||[]).find(n=>String(n.slug||'')===String(slug||''));if(!x)return layout('Không tìm thấy',`<div class="panel"><h1>Không tìm thấy bài viết</h1><p>Bài viết có thể đã được thay thế hoặc xóa.</p><a class="btn" href="/tin-tuc">Quay lại tin tức</a></div>`);return layout(x.title,`<article class="article"><span class="tag">${esc(x.category)}</span><h1>${esc(x.title)}</h1><time>${esc(x.date)}</time>${x.image?`<img class="articleimg" src="${esc(x.image)}" alt="">`:''}<p class="lead">${esc(x.excerpt)}</p>${Array.isArray(x.body)?x.body.map(p=>`<p>${esc(p)}</p>`).join(''):`<p>${esc(x.body||'')}</p>`}</article>`)}
function intro(){return layout('Giới thiệu',`<article class="article"><h1>${esc(data.site?.shortName)}</h1><p class="lead">${esc(data.site?.motto)}</p><p>Trung tâm Phục vụ Hành chính công xã Lam Thành là đầu mối tiếp nhận, hướng dẫn và trả kết quả thủ tục hành chính cho người dân, tổ chức.</p><p>Website cung cấp thông tin thủ tục, văn bản, lịch công tác, tra cứu hồ sơ và kênh phản ánh, kiến nghị.</p></article>`)}
function docs(){return layout('Văn bản',`<div class="sectionhead"><h1>Văn bản điều hành</h1></div><div class="tablewrap"><table><thead><tr><th>Số hiệu</th><th>Trích yếu</th><th>Loại</th><th>Cơ quan</th><th>Ngày</th></tr></thead><tbody>${(data.docs||[]).map(x=>`<tr><td>${esc(x.code)}</td><td>${esc(x.title)}</td><td>${esc(x.type)}</td><td>${esc(x.issuer)}</td><td>${esc(x.date)}</td></tr>`).join('')}</tbody></table></div>`)}
function procedures(){return layout('Thủ tục hành chính',`<div class="sectionhead"><h1>Thủ tục hành chính</h1></div><input class="search" placeholder="Tìm theo tên, mã hoặc lĩnh vực" oninput="filterProc(this.value)"><div id="proc" class="tablewrap"></div>`)}
function renderProc(q=''){const rows=(data.procedures||[]).filter(x=>Object.values(x).join(' ').toLowerCase().includes(q.toLowerCase()));document.getElementById('proc').innerHTML=`<table><thead><tr><th>Mã</th><th>Tên thủ tục</th><th>Lĩnh vực</th><th>Thời hạn</th><th>Lệ phí</th><th>Trực tuyến</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.code)}</td><td>${esc(x.name)}</td><td>${esc(x.field)}</td><td>${esc(x.duration)}</td><td>${esc(x.fee)}</td><td>${esc(x.online)}</td></tr>`).join('')}</tbody></table>`}
window.filterProc=q=>renderProc(q);
function schedule(){return layout('Lịch công tác',`<div class="sectionhead"><h1>Lịch công tác</h1></div><div class="schedule">${(data.schedule||[]).map(d=>`<section><h3>${esc(d.day)} <span>${esc(d.date)}</span></h3>${(d.items||[]).map(i=>`<div class="event"><b>${esc(i.time)}</b><div>${esc(i.text)}<small>${esc(i.place)}</small></div></div>`).join('')}</section>`).join('')}</div>`)}
async function lookup(){return layout('Tra cứu hồ sơ',`<div class="lookup panel"><h1>Tra cứu hồ sơ</h1><p>Nhập mã hồ sơ để kiểm tra tình trạng.</p><div class="actions"><input id="lookupCode" class="field" placeholder="Ví dụ: 2026-000123"><button class="btn" onclick="doLookup()">Tra cứu</button></div><div id="lookupResult"></div></div>`)}
window.doLookup=async()=>{const c=document.getElementById('lookupCode').value.trim();const el=document.getElementById('lookupResult');try{const r=await api('/lookup?code='+encodeURIComponent(c));el.innerHTML=r.found?`<div class="panel success"><b>${esc(r.item.code)}</b><p>${esc(r.item.name)} · ${esc(r.item.procedure)}</p><p>Trạng thái: <strong>${esc(r.item.status)}</strong></p><p>${esc(r.item.note)}</p></div>`:`<div class="panel error">Không tìm thấy hồ sơ.</div>`}catch(e){el.innerHTML=`<div class="panel error">${esc(e.message)}</div>`}};
function contact(){return layout('Phản ánh, kiến nghị',`<div class="twocol"><div class="panel"><h1>Gửi phản ánh</h1><label>Họ tên<input id="fbname" class="field"></label><label>Liên hệ<input id="fbcontact" class="field"></label><label>Nội dung<textarea id="fbcontent" class="field"></textarea></label><button class="btn" onclick="sendFeedback()">Gửi phản ánh</button><div id="fbmsg"></div></div><div class="panel"><h2>Thông tin</h2><p>${esc(data.site?.address)}</p><p>${esc(data.site?.email)}</p><p>${esc(data.site?.hotline)}</p></div></div>`)}
window.sendFeedback=async()=>{try{await api('/feedback',{method:'POST',body:JSON.stringify({name:document.getElementById('fbname').value,contact:document.getElementById('fbcontact').value,content:document.getElementById('fbcontent').value})});document.getElementById('fbmsg').innerHTML='<p class="notice success">Đã gửi phản ánh.</p>'}catch(e){document.getElementById('fbmsg').innerHTML='<p class="notice error">'+esc(e.message)+'</p>'}};
function dashboard(){return `<div class="metrics"><div><b>${data.stats?.received||0}</b><span>Hồ sơ tiếp nhận</span></div><div><b>${data.stats?.resolved||0}</b><span>Đã giải quyết</span></div><div><b>${data.stats?.online||0}</b><span>Trực tuyến</span></div><div><b>${data.stats?.processing||0}</b><span>Đang xử lý</span></div></div>`}
function login(){return `<div class="login"><div class="panel"><h1>Quản trị website</h1><p>Đăng nhập để quản lý nội dung.</p><label>Tài khoản<input id="u" class="field"></label><label>Mật khẩu<input id="p" type="password" class="field"></label><button class="btn" onclick="doLogin()">Đăng nhập</button><div id="loginMsg"></div></div></div>`}
window.doLogin=async()=>{try{const r=await api('/login',{method:'POST',body:JSON.stringify({username:document.getElementById('u').value,password:document.getElementById('p').value})});auth=r;await loadAdmin();renderAdmin()}catch(e){document.getElementById('loginMsg').innerHTML='<p class="notice error">'+esc(e.message)+'</p>'}};
async function loadAdmin(){const r=await api('/admin-data');data={...data,...r.data,feedback:r.feedback||[],lookupRecords:r.lookupRecords||[]};meta=r.meta;const s=await api('/session');auth={...auth,...s};if(auth.role==='admin'){try{auth.accounts=(await api('/accounts')).items}catch{auth.accounts=[]}}}
function adminShell(content){const tabs=[['overview','Tổng quan'],['news','Tin tức'],['docs','Văn bản'],['procedures','TTHC'],['schedule','Lịch công tác'],['feedback','Phản ánh'],['lookup','Tra cứu hồ sơ'],['navigation','Menu'],['banners','Banner'],['quickLinks','Liên kết nhanh'],['settings','Website'],['media','Thư viện ảnh']];if(auth?.role==='admin')tabs.push(['accounts','Tài khoản'],['backup','Sao lưu']);return `<div class="admin"><div class="adminhead wrap"><div><h1>Quản trị website</h1><span class="status">${esc(auth?.user)} · ${esc(auth?.role)}</span></div><button class="btn" onclick="logout()">Đăng xuất</button></div><div class="adminlayout wrap"><aside class="side">${tabs.map(t=>`<button onclick="adminTab('${t[0]}')">${t[1]}</button>`).join('')}</aside><section id="admincontent">${content}</section></div></div>`}
window.adminTab=async t=>{tab=t;let c='';if(t==='overview')c=dashboard();else if(t==='news')c=crudList('Tin tức',data.news,'title','news');else if(t==='docs')c=crudList('Văn bản',data.docs,'title','docs');else if(t==='procedures')c=crudList('Thủ tục hành chính',data.procedures,'name','procedures');else if(t==='schedule')c=crudList('Lịch công tác',data.schedule,'day','schedule');else if(t==='feedback')c=crudList('Phản ánh',data.feedback,'content','feedback');else if(t==='lookup')c=crudList('Hồ sơ tra cứu',data.lookupRecords,'code','lookup');else if(t==='navigation')c=crudList('Menu',data.navigation,'label','navigation');else if(t==='banners')c=crudList('Banner',data.banners,'title','banners');else if(t==='quickLinks')c=crudList('Liên kết nhanh',data.quickLinks,'title','quickLinks');else if(t==='settings')c=settingsForm();else if(t==='accounts')c=accountsForm();else if(t==='backup')c=`<div class="panel"><h2>Sao lưu & khôi phục</h2><button class="btn" onclick="backup()">Tải JSON</button><input type="file" accept="application/json" onchange="restore(this)"></div>`;else if(t==='media')c=`<div class="panel"><h2>Thư viện ảnh</h2><input type="file" accept="image/*" onchange="uploadMedia(this)"><div id="mediaGrid" class="mediaGrid"></div></div>`;document.getElementById('admincontent').innerHTML=c;if(t==='media')loadMedia()};
function crudList(title,arr,key,type){return `<div class="panel"><div class="sectionhead"><h2>${title}</h2><button class="btn" onclick="addItem('${type}')">+ Thêm</button></div><div class="adminlist">${(arr||[]).map((x,i)=>`<div><span><b>${esc(x[key])}</b><small>${esc(x.category||x.field||x.status||x.date||'')}</small></span><button onclick="editItem('${type}',${i})">Sửa</button><button onclick="delItem('${type}',${i})">Xóa</button></div>`).join('')}</div></div>`}
const forms={news:[['title','Tiêu đề'],['category','Chuyên mục'],['date','Ngày'],['image','Ảnh'],['excerpt','Tóm tắt'],['body','Nội dung']],navigation:[['label','Tên menu'],['url','Đường dẫn'],['order','Thứ tự']],banners:[['title','Tiêu đề'],['text','Mô tả'],['image','Ảnh'],['buttonText','Nút'],['buttonUrl','Đường dẫn nút'],['order','Thứ tự']],quickLinks:[['title','Tiêu đề'],['text','Mô tả'],['url','Đường dẫn'],['order','Thứ tự']],docs:[['code','Số hiệu'],['title','Trích yếu'],['type','Loại'],['issuer','Cơ quan'],['date','Ngày']],procedures:[['code','Mã'],['name','Tên'],['field','Lĩnh vực'],['duration','Thời hạn'],['fee','Lệ phí'],['online','Trực tuyến']],schedule:[['day','Ngày'],['date','Ngày tháng']],feedback:[['name','Họ tên'],['topic','Chủ đề'],['status','Trạng thái'],['content','Nội dung']],lookup:[['code','Mã hồ sơ'],['name','Người nộp'],['procedure','Thủ tục'],['received','Tiếp nhận'],['status','Trạng thái'],['updated','Cập nhật'],['note','Ghi chú']]};
let edit={type:null,index:null};
window.addItem=t=>{edit={type:t,index:-1};showEditor()};window.editItem=(t,i)=>{edit={type:t,index:i};showEditor()};
function showEditor(){const a=data[{news:'news',docs:'docs',procedures:'procedures',schedule:'schedule',feedback:'feedback',lookup:'lookup',navigation:'navigation',banners:'banners',quickLinks:'quickLinks'}[edit.type]]||[];const x=edit.index<0?{}:a[edit.index];const fs=forms[edit.type]||[];document.getElementById('admincontent').innerHTML=`<div class="panel"><h2>${edit.index<0?'Thêm':'Sửa'} ${esc(edit.type)}</h2>${fs.map(([k,l])=>`<label>${l}${k==='content'||k==='excerpt'||k==='note'?`<textarea id="f_${k}" class="field">${esc(x[k]||'')}</textarea>`:`<input id="f_${k}" class="field" value="${esc(x[k]||'')}">`}</label>`).join('')}<div class="actions"><button class="btn" onclick="saveItem()">Lưu</button><button class="btn ghost" onclick="adminTab('${edit.type}')">Hủy</button></div></div>`}
window.saveItem=async()=>{const t=edit.type,key={news:'news',docs:'docs',procedures:'procedures',schedule:'schedule',feedback:'feedback',lookup:'lookup',navigation:'navigation',banners:'banners',quickLinks:'quickLinks'}[t];const a=data[key]||[];const old=edit.index<0?{}:a[edit.index];const x={...old};(forms[t]||[]).forEach(([k])=>x[k]=document.getElementById('f_'+k)?.value||'');if(t==='news'){x.slug=x.slug||x.title.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');x.body=x.body||[x.excerpt||''];}if(edit.index<0)a.push(x);else a[edit.index]=x;if(t==='feedback'||t==='lookup'){try{await api('/'+t,{method:edit.index<0?'POST':'PUT',body:JSON.stringify(x)});await loadAdmin()}catch(e){return alert(e.message)}}else if(await save()){ }adminTab(t)};
window.delItem=async(t,i)=>{if(!confirm('Xóa mục này?'))return;const key=t==='news'?'news':t==='docs'?'docs':t==='procedures'?'procedures':t==='schedule'?'schedule':t==='navigation'?'navigation':t==='banners'?'banners':t==='quickLinks'?'quickLinks':null;if(t==='feedback'||t==='lookup'){try{await api('/'+t+'?id='+encodeURIComponent(data[t][i].id),{method:'DELETE'});await loadAdmin()}catch(e){return alert(e.message)}}else if(key){data[key].splice(i,1);await save()}adminTab(t)};
async function save(){try{const r=await api('/content',{method:'PUT',body:JSON.stringify({data,version:meta.version})});meta=r.meta;return true}catch(e){alert(e.message);return false}}
function settingsForm(){return `<div class="panel"><h2>Thông tin website</h2>${['name','shortName','commune','province','motto','address','hotline','email','hours'].map(k=>`<label>${k}<input id="s_${k}" class="field" value="${esc(data.site?.[k]||'')}"></label>`).join('')}<label>Tiêu đề banner<input id="s_bannerTitle" class="field" value="${esc(data.settings?.bannerTitle||'')}"></label><label>Nội dung banner<textarea id="s_bannerText" class="field">${esc(data.settings?.bannerText||'')}</textarea></label><button class="btn" onclick="saveSettings()">Lưu</button></div>`}
window.saveSettings=async()=>{for(const k of ['name','shortName','commune','province','motto','address','hotline','email','hours'])data.site[k]=document.getElementById('s_'+k).value;data.settings.bannerTitle=document.getElementById('s_bannerTitle').value;data.settings.bannerText=document.getElementById('s_bannerText').value;if(await save())alert('Đã lưu')};
function accountsForm(){if(auth.role!=='admin')return '<div class="panel">Không có quyền.</div>';return `<div class="panel"><h2>Tài khoản</h2>${(auth.accounts||[]).map(x=>`<div class="adminrow"><span><b>${esc(x.username)}</b><small>${esc(x.displayName)} · ${esc(x.role)}</small></span><button onclick="changePass('${esc(x.username)}')">Đổi mật khẩu</button></div>`).join('')}<h3>Thêm tài khoản</h3><input id="nu" class="field" placeholder="username"><input id="np" type="password" class="field" placeholder="mật khẩu ≥10 ký tự"><select id="nr" class="field"><option>editor</option><option>admin</option></select><button class="btn" onclick="addAccount()">Tạo</button></div>`}
window.addAccount=async()=>{try{await api('/accounts',{method:'POST',body:JSON.stringify({username:nu.value,password:np.value,role:nr.value})});await loadAdmin();adminTab('accounts')}catch(e){alert(e.message)}};window.changePass=async u=>{const p=prompt('Mật khẩu mới (≥10 ký tự):');if(p)try{await api('/accounts',{method:'PUT',body:JSON.stringify({username:u,password:p})});alert('Đã đổi mật khẩu')}catch(e){alert(e.message)}};
window.backup=async()=>{const r=await api('/backup');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));a.download='lamthanh-backup.json';a.click()};window.restore=async input=>{const f=input.files?.[0];if(!f)return;try{const r=await api('/backup',{method:'POST',body:await f.text()});alert(r.ok?'Đã khôi phục':'Thất bại');await loadAdmin();adminTab('overview')}catch(e){alert(e.message)}};
window.uploadMedia=async input=>{const f=input.files?.[0];if(!f)return;const fd=new FormData();fd.append('file',f);try{const r=await fetch('/.netlify/functions/cms/media',{method:'POST',body:fd,credentials:'include'});if(!r.ok)throw new Error(await r.text());loadMedia()}catch(e){alert(e.message)}};async function loadMedia(){try{const r=await api('/media');document.getElementById('mediaGrid').innerHTML=r.items.map(x=>`<figure><img src="${esc(x.url)}"><figcaption>${esc(x.key)}</figcaption></figure>`).join('')}catch(e){document.getElementById('mediaGrid').innerHTML='<p>'+esc(e.message)+'</p>'}}
window.logout=async()=>{await api('/logout',{method:'POST'});location.href='/quan-tri'};
async function admin(){try{const s=await api('/session');if(!s.authenticated)return login();auth=s;await loadAdmin();return adminShell(dashboard())}catch(e){return login()}}
async function render(){await load();const p=location.pathname.replace(/\/$/,'')||'/';let html=p==='/'?home():p==='/gioi-thieu'?intro():p==='/tin-tuc'?news():p.startsWith('/tin-tuc/')?newsDetail(decodeURIComponent(p.slice('/tin-tuc/'.length))):p==='/van-ban'?docs():p==='/thu-tuc'?procedures():p==='/lich-cong-tac'?schedule():p==='/tra-cuu'?await lookup():p==='/lien-he'||p==='/phan-anh'?contact():p==='/quan-tri'?await admin():layout('404','<div class="panel"><h1>Không tìm thấy trang</h1></div>');document.getElementById('app').innerHTML=html;if(p==='/thu-tuc')renderProc();}
document.addEventListener('click',e=>{const a=e.target.closest('a[href]');if(a&&a.origin===location.origin&&!a.target&&a.getAttribute('href')!=='#'){e.preventDefault();history.pushState({},'',a.pathname);render()}});addEventListener('popstate',render);render();
